pipeline:
  run-tests:
    image: node:6.3.0
    commands:
      - cd ./api && npm i --quiet
      - npm test


#  publish-api-docker:
#    image: plugins/docker
#    username: ${DOCKER_USERNAME}
#    password: ${DOCKER_PASSWORD}
#    email: ${DOCKER_EMAIL}
#    repo: n01an/drone-node-api
#    tags:
#      - latest
#    dockerfile: ./api/Dockerfile
#    context: ./api/

  slack-notification:
    image: plugins/slack
    settings:
      webhook: ${WEBHOOK}
      username: drone-ci
      channel: general
      icon_emoji: ":rocket:"
