pipeline:
#  run-tests:
#    image: node:6.3.0
#    commands:
#      - cd ./api && npm i --quiet
#      - npm test

#  publish-api-docker:
#    image: plugins/docker
#    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
#    repo: n01an/drone-node-api
#    tags:
#      - latest
#    dockerfile: ./api/Dockerfile
#    context: ./api/

  slack_notification:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: general
    link_names: true
#      template:  >
#        {{#success build.status}}
#          build {{build.number}} succeeded. Good job. <@r.bovda>
#        {{else}}
#          build {{build.number}} failed. Fix me please. <@devops>
#        {{/success}}